module.exports = {

    'secret': 'SINIGANGNAMANOKNAMAYBABOYAT#12PAMPALASANAPINAKULUANNANG5ORASHANGGANGSAMAABOTANGNINANAISNALAMBOT',
    'database': 'localhost:27017/authentication',
    'GOOGLE_SECRET': 'hWebd7iWiLPHd1KHI6FnWyO5'

};